# Supervised Learning

## ANN

In [24]:
import pandas as pd
import numpy as np
import tensorflow as tf

tf.__version__

'2.3.0'

In [2]:
data = pd.read_csv('Churn_Modelling.csv')

data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [3]:
X = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
X.shape

(10000, 10)

In [26]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X[:, 2] = le.fit_transform(X[:, 2])

X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], 
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [28]:
X.shape

(10000, 12)

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=42)

### Always Feature Scale for Neural Nets

In [30]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(units=8, activation='relu'))
model.add(tf.keras.layers.Dense(units=8, activation='relu'))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [33]:
model.compile(optimizer='adam', 
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [34]:
model.fit?

In [37]:
model.fit(x=X_train, y=y_train, epochs=25)

Epoch 1/25
250/250 [==============================] - 0s 858us/step - loss: 0.3348 - accuracy: 0.8629
Epoch 2/25
250/250 [==============================] - 0s 908us/step - loss: 0.3347 - accuracy: 0.8634
Epoch 3/25
250/250 [==============================] - 0s 877us/step - loss: 0.3342 - accuracy: 0.8631
Epoch 4/25
250/250 [==============================] - 0s 954us/step - loss: 0.3343 - accuracy: 0.8625
Epoch 5/25
250/250 [==============================] - 0s 922us/step - loss: 0.3339 - accuracy: 0.8614
Epoch 6/25
250/250 [==============================] - 0s 921us/step - loss: 0.3340 - accuracy: 0.8625
Epoch 7/25
250/250 [==============================] - 0s 895us/step - loss: 0.3332 - accuracy: 0.8626
Epoch 8/25
250/250 [==============================] - 0s 900us/step - loss: 0.3335 - accuracy: 0.8644
Epoch 9/25
250/250 [==============================] - 0s 938us/step - loss: 0.3329 - accuracy: 0.8621
Epoch 10/25
250/250 [==============================] - 0s 929us/step - loss: 0.332

In [57]:
# France, 600, Male, 
# Credit:600, Age:40,
# Tenure:3, Bal:6000, Pr:2, Cr:1, Active:1, 50000

single_res = [[1, 0, 0, 600, 1, 40, 3, 6000, 2, 1, 1, 50000]]

print(model.predict(sc.transform(single_res)) > 0.5)

[[False]]


In [62]:
y_pred = model.predict(X_test)

y_pred = y_pred > 0.5
y_pred = y_pred.astype(int)

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)

print(cm)

accuracy_score(y_test, y_pred)

[[1600    7]
 [ 342   51]]


0.8255

## CNN

### Load the data

In [ ]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255,
                                  shear_range=0.2,
                                  zoom_range=0.2,
                                  horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

training